name: calculator
description: A simple calculator to showcase various programming concepts.
version: 0.0.1

publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
